/* ============================================================
   HUNTER HUNTED: IRON TIDE — Walkthrough content
   All section content lives here. Section components in
   sections.jsx read this structure.
   ============================================================ */

window.SECTIONS = [
  {
    id: "premise",
    num: "01",
    title: "Premise & Setting",
    tagline: "An alternate Cold War that never went cold at sea.",
    classLine: "1955–1958 · German U-boat command sim",
    color: "accent",
  },
  {
    id: "timeline",
    num: "02",
    title: "Timeline",
    tagline: "From the Gersdorff bomb to the Iron Tide of '55.",
    classLine: "Point of divergence: 21 Mar 1943",
    color: "default",
  },
  {
    id: "variants",
    num: "03",
    title: "The Boats",
    tagline: "Atlantik hero · five-hull ladder.",
    classLine: "Player boat + 4 variants",
    color: "blue",
    links: [
      { id: "hero", label: "Atlantik (player)" },
      { id: "kw",   label: "Küstenwolf" },
      { id: "sf",   label: "Silberfisch" },
      { id: "fw",   label: "Fernwolf" },
      { id: "wh",   label: "Walhall" },
    ],
  },
  {
    id: "tech",
    num: "04",
    title: "Tech & Systems",
    tagline: "Propulsion, sensors, weapons, countermeasures — 1955 spec.",
    classLine: "GHG · Walter · Vorhaltrechner · Bold-VII",
    color: "blue",
    links: [
      { id: "prop", label: "Propulsion" },
      { id: "sens", label: "Sensors" },
      { id: "wpns", label: "Weapons" },
      { id: "cm",   label: "Countermeasures" },
    ],
  },
  {
    id: "phases",
    num: "05",
    title: "Five Tactical Phases",
    tagline: "Cruise · Stalk · Attack · Evade · Recover.",
    classLine: "The patrol rhythm",
    color: "accent",
    links: [
      { id: "cruise",  label: "Cruise" },
      { id: "stalk",   label: "Stalk" },
      { id: "attack",  label: "Attack" },
      { id: "evade",   label: "Evade" },
      { id: "recover", label: "Recover" },
    ],
  },
  {
    id: "stations",
    num: "06",
    title: "Gameplay Stations",
    tagline: "Captain, Sonar, Navigator, Engineer, Torpedo.",
    classLine: "Five-player co-op · 5 of 5 designed",
    color: "accent",
    links: [
      { id: "CAPTAIN",   label: "Captain" },
      { id: "SONAR",     label: "Sonar" },
      { id: "NAVIGATOR", label: "Navigator" },
      { id: "ENGINEER",  label: "Engineer" },
      { id: "TORPEDO",   label: "Torpedo" },
    ],
  },
  {
    id: "comms",
    num: "07",
    title: "Cross-Station Comms",
    tagline: "Dual-channel — voice is the soul; data is the spine.",
    classLine: "~48 flows · 35% push · 65% voice-only",
    color: "default",
  },
  {
    id: "crew",
    num: "08",
    title: "Crew & Card Events",
    tagline: "Named men, generic pools, dispatch under fire.",
    classLine: "57 hands · 4 specialty domains",
    color: "default",
  },
  {
    id: "tone",
    num: "09",
    title: "Tone & Atmosphere",
    tagline: "Quiet attrition, not action heroism.",
    classLine: "Das Boot · 1955 · Imperial Eagle",
    color: "default",
  },
  {
    id: "open",
    num: "10",
    title: "Open Questions",
    tagline: "What's still being designed.",
    classLine: "Live design doc — Epic 10",
    color: "blue",
  },
  {
    id: "identity",
    num: "11",
    title: "Visual Identity",
    tagline: "Logo concepts and naming for review.",
    classLine: "6 marks · 5 name variants",
    color: "accent",
    links: [
      { id: "type",      label: "Typographic" },
      { id: "monogram",  label: "HH Monogram" },
      { id: "periscope", label: "Periscope Eye" },
      { id: "sonar",     label: "Sonar Arc" },
      { id: "tide",      label: "Iron Tide" },
      { id: "seal",      label: "Tactical Seal" },
    ],
  },
];

window.TIMELINE = [
  { date: "21 Mar 1943", major: true, title: "Berlin Zeughaus — the bomb succeeds",
    body: "Colonel von Gersdorff detonates two concealed charges in his greatcoat at the Berlin Armoury. Hitler, Keitel, Dönitz, and several senior officials are killed instantly. Gersdorff dies in the blast." },
  { date: "Apr–Aug 1943", major: false, title: "The Beck regency consolidates",
    body: "The conservative-military conspiracy under Beck, Tresckow, and the Kreisau Circle fills the vacuum. SS dissolved over six weeks. Architects of the racial extermination programme tried in summary military courts. Goebbels dead. Bormann disappears. Göring retires to his estates." },
  { date: "Winter 1943", major: false, title: "Strategic withdrawal in the East",
    body: "Manstein and Rommel establish the Panther-Wotan Line: Narva — Lake Peipus — Pskov — Vitebsk — middle Dnieper — Kherson. Soviet counter-offensives through 1944 break against prepared positions." },
  { date: "6 June 1944", major: true, title: "Normandy repulsed",
    body: "Rommel, Inspector-General of Western Defences, deploys the panzer reserves forward. The Allies evacuate the Cotentin by 12 June. Eisenhower offers resignation; refused. Operation Dragoon fares no better." },
  { date: "Jan 1945", major: true, title: "Proclamation of the Kaiserreich",
    body: "Prince Louis Ferdinand of Prussia is proclaimed Kaiser Ludwig Ferdinand I at Potsdam. The regency dissolves. Imperial constitution restored; Reichstag with limited powers; NSDAP formally abolished." },
  { date: "Feb 1945", major: false, title: "Otto crowned in Vienna",
    body: "Otto von Habsburg returns from American exile and is crowned Kaiser of Austria-Hungary. The 'Twin Crowns' arrangement formalises a German-Austrian dual monarchy on paper." },
  { date: "1945–1948", major: false, title: "The Pacific stalemate",
    body: "Without atomic weapons, Operation Downfall is repeatedly postponed. Hirohito dies October 1945. Japan still controls Korea, Manchuria, eastern China, Indochina, the East Indies. The Home Islands become a starvation zone." },
  { date: "Aug 1946", major: false, title: "First Eastern Armistice — Stockholm Protocols",
    body: "Soviets and Germans sign a temporary cessation. Neither side calls it peace. Both immediately begin preparing for the next round." },
  { date: "Jul 1949 – Nov 1950", major: false, title: "Second Eastern War",
    body: "Soviet probes across the Dnieper escalate. A second armistice in November 1950 holds along essentially the same lines, with adjustments around Kyiv and Pskov." },
  { date: "1948 → present", major: false, title: "The sea war intensifies",
    body: "With the land fronts frozen, Allied strategy shifts entirely to maritime pressure. German strategy in turn becomes total commerce raiding — Dönitz's pre-war tonnage doctrine taken to its conclusion, with twelve years of accumulated investment in submarine technology." },
  { date: "Mar 1953", major: false, title: "Stalin dies; Taft inaugurated",
    body: "Malenkov succeeds Stalin. President Robert A. Taft (R-OH) takes office on a platform of 'ending the wars or winning them.' The Eden government in London manages imperial collapse — India gone, Palestine in civil war, Egypt has expelled the British from Suez." },
  { date: "1955", major: true, title: "The Iron Tide — playable now",
    body: "Sixteenth year of unbroken war at sea. ~220 Type XXI/M3 Atlantiks in commission. The Third Eastern War widely expected within two years. The world is tired. The war continues." },
  { date: "1958 (projected)", major: false, title: "Walhall launches",
    body: "First German nuclear-powered submarine, Type XXXI, projected commissioning late 1958. End-game campaign content." },
];

window.ATLANTIK_SPEC = [
  ["Crew", "57 · 3 watch sections"],
  ["Length", "78 m"],
  ["Displacement", "1,820 t submerged"],
  ["Sprint / cruise / creep", "17 · 8 · 3 kn"],
  ["Test depth", "240 m (crush ~330)"],
  ["Endurance", "60-day patrol w/ snorkel"],
  ["Tubes", "6 bow · 2 stern · 20 fish"],
  ["Fire control", "Vorhaltrechner M-7"],
  ["Hydrophone", "GHG · 56 elements/side"],
  ["ESM", "FuMB-7 panoramic"],
  ["Coating", "Alberich-IV anechoic"],
  ["Cipher", "Schlüsselgerät 51"],
];

window.VARIANTS = [
  { id: "kw", code: "XXIII/K2", name: "Küstenwolf", role: "Coastal Wolf",
    tone: "Claustrophobic, short, atmospheric.",
    blurb: "The entry-level boat. Two bow tubes, no reloads, 280 tons. Mediterranean and Baltic coastal work. Limited torpedo capacity teaches discipline; small acoustic signature makes it survivable in cluttered waters.",
    stats: { displ: "280 / 360 t", crew: 18, len: "38 m", speed: "12 / 4 kn", depth: "180 m", arm: "2 bow · 6 mines" },
    progression: 1 },
  { id: "at", code: "XXI/M3", name: "Atlantik", role: "Atlantic Workhorse",
    tone: "The main rhythm — cruise, stalk, attack, evade, recover.",
    blurb: "The fleet workhorse. ~220 in commission. The full feature set of modern U-boat combat. The standard against which all other boats are measured. The boat we design against first.",
    stats: { displ: "1,620 / 1,820 t", crew: 57, len: "78 m", speed: "17 / 8 / 3 kn", depth: "240 m", arm: "6 bow · 2 stern · 20 fish" },
    progression: 2, hero: true },
  { id: "sf", code: "XXVI-A", name: "Silberfisch", role: "Walter HTP sprint boat",
    tone: "Prestige assignment. T-Stoff is one valve away from killing everyone.",
    blurb: "24-knot submerged sprint for up to four hours on hydrogen-peroxide turbine. Fundamentally changes attack geometry — outruns destroyers underwater, attacks from impossible angles. Limited service, limited base support.",
    stats: { displ: "940 / 1,090 t", crew: 33, len: "56 m", speed: "24 sprint · 14 sus · 8 kn", depth: "210 m", arm: "6 bow · 12 fish" },
    progression: 4 },
  { id: "fw", code: "XXIX/F", name: "Fernwolf", role: "Far Wolf — long range",
    tone: "Vast operating areas, extended isolation, allied liaisons aboard.",
    blurb: "120-day patrols, 18,000 nm range. Kreislaufdiesel closed-cycle propulsion: six days submerged at 12 kn. Operates from Penang and Karachi. Some carry a Seeschlange cruise missile canister.",
    stats: { displ: "2,200 / 2,500 t", crew: 64, len: "92 m", speed: "15 / 12 / 8 / 3 kn", depth: "250 m", arm: "6 bow · 2 stern · 24 fish" },
    progression: 3 },
  { id: "wh", code: "XXXI", name: "Walhall", role: "Nuclear prototype",
    tone: "Late-campaign. The strategic answer.",
    blurb: "First German nuclear-powered submarine. Projected commissioning 1958. The end-game patrol — shakedown on the most advanced submarine in the world, with Allied intelligence services desperate to confirm her existence.",
    stats: { displ: "3,800 / 4,400 t (est)", crew: "~95", len: "~105 m", speed: "~28 kn sustained", depth: "~300 m", arm: "8 bow · 4 stern" },
    progression: 5 },
];

window.TECH_SECTIONS = [
  {
    id: "prop",
    title: "Propulsion",
    blurb: "Four propulsion families. The boat fights at three speeds and three risk tiers.",
    items: [
      { name: "Diesel-Electric", spec: "Standard fleet. 17 kn surfaced, 11 kn snorkelling, 17 kn submerged sprint with severe battery cost.",
        detail: "Two MAN diesels (~2,200 hp each) on the surface or snorkel. Two Siemens-Schuckert electric motors submerged. Creep motors below for near-silent stalking. Battery management remains the captain's strategic concern — drain too much in a chase and you have nothing left for the evasion that follows." },
      { name: "Walter HTP", spec: "Sprint AIP. 22–24 kn submerged for up to 4 hours on hydrogen peroxide.",
        detail: "Hydrogen peroxide decomposed catalytically, oxygen combusts with diesel, hot gases drive a turbine. 60 s warmup. 30 min cooldown. T-Stoff is corrosive and combusts on contact with contaminants — there is a manual emergency dump system. Crews speak of Walter-boat losses that produce no debris." },
      { name: "Kreislaufdiesel", spec: "Sustained AIP. 14–16 kn for 4–6 days on stored liquid oxygen.",
        detail: "The conservative answer to Walter. Diesel engine running on stored LOX rather than atmospheric oxygen, exhaust gases scrubbed of CO₂ via chemical absorbent loop. By 1955 a small number of fleet boats carry it as a secondary system. Long-range Fernwolf patrols make particular use." },
      { name: "Nuclear (in development)", spec: "Type XXXI Walhall, 1958 projected. Reactor-limited endurance measured in months.",
        detail: "Kaiserliche Reichswerke Atomprogramm has produced a working naval reactor. Rumours, intelligence reports, and ship-watcher sightings are part of the lore — no nuclear boats are operational in the main timeframe." },
    ]
  },
  {
    id: "sens",
    title: "Sensors",
    blurb: "Modern crew can develop a complete tactical picture without ever raising a periscope.",
    items: [
      { name: "GHG (Gruppenhorchgerät)", spec: "Passive hydrophone, 56 elements per side, electronic beamforming.",
        detail: "Convoy 30–40 nm, freighter 15–25, escort at search speed 8–15, escort silent-stalking 2–5, submerged sub on creep 1–3. A skilled Horcher identifies ship type, screw count, blade rate, engine type, and sometimes individual ship by acoustic signature. The Geräuschbuch is the acoustic library carried aboard every boat." },
      { name: "KDB directional", spec: "Rotating deck-mounted array for sharp bearing on a single contact.",
        detail: "Used during attack development to lock one bearing tightly while GHG continues to sweep elsewhere." },
      { name: "S-Gerät active", spec: "Rare use — single ping for ranging, advertises position.",
        detail: "Frequency-agile across multiple bands within a single pulse train. Used for under-ice navigation, for in-extremis sub-vs-sub combat, or when passive bearings cannot resolve range." },
      { name: "Sonar intercept", spec: "Knows you're being pinged ~30 s before the enemy gets a return.",
        detail: "Identifies the ship class doing the pinging by sonar fingerprint. Sound travels one-way to the U-boat versus two-way to the searcher — the captain gets warning before the enemy gets information." },
      { name: "Periscopes", spec: "Attack scope (thin, low-light) + search scope (thicker, integrated ESM).",
        detail: "Modern doctrine is 'oben, schwenken, unten' (up, sweep, down) in 6–8 seconds. The attack scope has stadimeter range, integrated handgrip controls, and a button that commits the current bearing to the Vorhaltrechner." },
      { name: "FuMB-7 ESM", spec: "Panoramic radar warning. Frequency, PRF, pulse width, bearing.",
        detail: "When an Allied aircraft radar shifts from search to track, the operator calls 'Ortung!' and the dive klaxon sounds. Direction-finding allows precise bearings on intercepted emissions." },
      { name: "Navigation suite", spec: "Gyro, Sonne radio nav, celestial, inertial prototype.",
        detail: "Sonne gives 2–5 nm fix at long range. The newest Atlantik M3 boats carry a prototype inertial unit derived from V-2 guidance work — dead-reckoning to within a nautical mile over a 72-hour submerged patrol." },
    ]
  },
  {
    id: "wpns",
    title: "Weapons",
    blurb: "Five torpedo types, mines, one cruise missile. Plus the Vorhaltrechner M-7.",
    items: [
      { name: "Zaunkönig III (T11)", spec: "Electric · acoustic-homing · anti-warship. 8 km · 25 kn · 280 kg.",
        detail: "Counter-countermeasure logic rejects steady-tone signals — Allied 'Foxer' decoys produce a continuous warble the seeker can discriminate from a real ship's signature." },
      { name: "Lerche II (T15)", spec: "Electric · wire-guided · acoustic terminal. 14 km · 22 kn · 260 kg.",
        detail: "Wire allows the WO to steer past noisemakers and decoys until the seeker acquires the real target. Two wire-guidance consoles per boat — only two Lerche shots can be in flight simultaneously." },
      { name: "Schlange (T16)", spec: "Steam · pattern runner. 12 km · 30 kn · 280 kg.",
        detail: "Programmable serpentine, snake, or circling pattern across a target track. Used against convoys for multi-hit probability." },
      { name: "Steinbutt (T13)", spec: "Anti-submarine · wire-guided. 10 km · 24 kn · 240 kg.",
        detail: "Seeker optimised against submerged acoustic signatures (much quieter, lower-frequency). Designed for sub-vs-sub." },
      { name: "TMC mine", spec: "1,000 kg warhead · magnetic, acoustic, pressure triggers.",
        detail: "Torpedo-tube-launched moored mine. Programmable delays and counters defeat sweeping. Mine-laying missions involve programming an 8–16 mine pattern, 200–400 m spacing." },
      { name: "Vorhaltrechner M-7", spec: "Electromechanical TDC · 4-target tracking · salvo coordination.",
        detail: "Sonar integration: bearings from GHG can be fed directly. Wire-guidance integration: after a Lerche launches, the WO can fly the torpedo manually while the M-7 continues computing updated solutions. A skilled WO/sonar team can develop a complete fire-control solution against an unseen target using sonar alone — the Lauschangriff." },
      { name: "Seeschlange", spec: "Cruise missile · 200 km · 500 kg warhead · CEP 1–2 km.",
        detail: "Pulse-jet weapon descended from the V-1. Boat must surface for ~90 s during launch — a dangerous interval. After launch, immediate crash dive. Useful only against large fixed targets." },
    ]
  },
  {
    id: "cm",
    title: "Countermeasures",
    blurb: "How you survive after they know you're there.",
    items: [
      { name: "Bold-VII mobile decoy", spec: "4-tube launcher · selectable surfaced/snorkel/submerged signature.",
        detail: "Self-propelled noisemaker swims a programmed course (typically 6 kn straight for 8 minutes) broadcasting a recorded U-boat signature. Standard tactic: launch, turn 90°, go silent, let the decoy lead the searchers away." },
      { name: "Sieglinde towed", spec: "Continuous broadcast · ≤ 6 kn speed cap.",
        detail: "Larger, continuous broadcast decoy on a cable behind the boat. Useful during prolonged evasion. Exceeding the cap breaks the decoy off." },
      { name: "Alberich-IV coating", spec: "Anechoic rubber tiles · 30–40% detection range reduction.",
        detail: "Absorbs Allied active sonar, dampens internal noise. Tiles occasionally come loose at depth or under explosive shock — a partially-clad boat has a worse signature than no tiles at all. Crews are protective of integrity; pre-patrol inspections are thorough." },
      { name: "Silent running (Stufe 1/2/3)", spec: "Graduated discipline — what shuts down at each level.",
        detail: "Each level progressively shuts down more machinery. Cooking stops at Stufe 2; toilet flushing stops at Stufe 1. Stufe 1 is the deep evasion mode — only essential systems, all hands lying down." },
      { name: "Deep diving", spec: "Test 240 m · crush ~330 m · thermal layer 60–120 m.",
        detail: "Allied ASW weapons are typically set for 80–150 m; going deep often takes the boat below the depth-charge envelope. The thermal layer adds acoustic shielding." },
    ]
  },
];

window.PHASES = [
  { id: "cruise",  short: "Cruise",   pct: "🔵",
    headline: "On patrol, no contacts.",
    body: "Snorkelling at night to charge batteries, submerged deep during daylight. Long stretches of routine with periodic sonar evaluation. Crew morale is the central management problem; cleaning, drills, and the few small luxuries (the modern fleet boat has refrigeration and a small ice-cream machine that crews adore) matter.",
    loads: { CAPTAIN: 3, SONAR: 3, NAVIGATOR: 3, ENGINEER: 4, TORPEDO: 3 },
    hot: ["ENGINEER"] },
  { id: "stalk",   short: "Stalk",    pct: "🟡",
    headline: "A target has been detected.",
    body: "The plot intensifies, the WO begins developing fire-control solutions, the captain spends time at the attack scope and at the Vorhaltrechner. Tempo accelerates. Battery and oxygen are managed against anticipated post-attack requirements.",
    loads: { CAPTAIN: 4, SONAR: 3, NAVIGATOR: 4, ENGINEER: 2, TORPEDO: 6 },
    hot: ["SONAR", "NAVIGATOR", "TORPEDO"] },
  { id: "attack",  short: "Attack",   pct: "🔴",
    headline: "Battle stations. Short, intense, decisive.",
    body: "Final approach, torpedoes fired, immediate course change for evasion. The Captain–Torpedo–Sonar verbal triangle is at peak. Navigator and Engineer feed support data via push. ~60–120 s of peak verbal density.",
    loads: { CAPTAIN: 4, SONAR: 4, NAVIGATOR: 3, ENGINEER: 3, TORPEDO: 7 },
    hot: ["CAPTAIN", "TORPEDO", "SONAR"] },
  { id: "evade",   short: "Evade",    pct: "🟠",
    headline: "Depth charges, sonar pings, sonobuoys, helicopter dipping.",
    body: "Bold decoys deployed at intervals. Silent ship discipline. Deep diving. Hours of held breath. Pure tension. Engineer working blow, depth and silent levels. Sonar tracks escorts. Captain makes evasion calls. Torpedo retains decoy duties.",
    loads: { CAPTAIN: 4, SONAR: 5, NAVIGATOR: 2, ENGINEER: 3, TORPEDO: 3 },
    hot: ["ENGINEER", "SONAR", "CAPTAIN"] },
  { id: "recover", short: "Recover",  pct: "⚫",
    headline: "Contact broken, damage assessed, casualties tallied.",
    body: "The exhaustion phase. Engineer triages. Captain receives report. Sonar verifies escape. Navigator plots course home or for the next grid. Crew gameplay peak #2: move bodies to damage control and reload prep. Casualty grief moments.",
    loads: { CAPTAIN: 3, SONAR: 2, NAVIGATOR: 1, ENGINEER: 2, TORPEDO: 2 },
    hot: ["ENGINEER"] },
];

window.STATIONS = [
  { id: "CAPTAIN", role: "Kommandant",
    char: "Decision-maker. Command authority, periscope, tactical reading.",
    panels: ["Plotting table — tactical board", "Periscope nacelle (search + attack)", "BdU clipboard inbox", "Wall instruments (read-only)"],
    work: ["Speed/depth/course orders", "Fire & decoy commands", "Crew dispatch (drag-and-drop)", "Wolf-pack signal routing"],
    color: "accent",
  },
  { id: "SONAR", role: "Horchraum + FuMB",
    char: "The ears — acoustic and electromagnetic. Sonar room is dim red, headphones, magic-eye signal-strength.",
    panels: ["GHG passive scope", "KDB directional", "S-Gerät active", "Sonar intercept", "FuMB-7 ESM panoramic"],
    work: ["Bearing classification", "Geräuschbuch matching", "'Ortung!' alert", "Decoy & layer tracking"],
    color: "default",
  },
  { id: "NAVIGATOR", role: "Navigator + Funker",
    char: "Plot, position, and now comms — radio/cipher/wolf-pack fold in here.",
    panels: ["Chart board / TMA plot", "Sonne radio nav", "Schnellschreiber HF burst", "Schlüsselgerät 51 cipher", "VLF inbox"],
    work: ["Position fixes", "TMA from bearings", "Encode/decode messages", "Wolf-pack UHF"],
    color: "default",
  },
  { id: "ENGINEER", role: "Leitender Ingenieur",
    char: "Power, propulsion, damage, silent running. Steady across all five phases.",
    panels: ["Diesel/electric/creep cluster", "Battery & motor panel", "Damage map", "Snorkel & trim"],
    work: ["Mode changes", "Battery management", "Silent-running Stufe", "Damage control · casualty triage"],
    color: "default",
  },
  { id: "TORPEDO", role: "Torpedo + WO @ Vorhaltrechner",
    char: "Five torpedo types, fire control, decoys, mines. Feast-or-famine load curve.",
    panels: ["Vorhaltrechner M-7", "Tube controls (×8)", "Wire-guide CRT consoles", "Bold-VII launcher panel"],
    work: ["Solution development", "Wire-guidance manual fly", "Reload tubes", "Decoy / mine ops"],
    color: "accent",
  },
];

window.COMMS_FLOWS = [
  // template A = push allowed, B = voice mandatory
  // edges between station IDs
  { from: "SONAR", to: "CAPTAIN", what: "Contact list", tpl: "A", phases: ["stalk","attack","evade"] },
  { from: "SONAR", to: "CAPTAIN", what: "'Ortung!' radar lock", tpl: "B", phases: ["cruise","stalk","evade"], urgent: true },
  { from: "NAVIGATOR", to: "CAPTAIN", what: "Position · decoded slips", tpl: "B", phases: ["cruise"] },
  { from: "ENGINEER", to: "CAPTAIN", what: "Battery · damage · casualties", tpl: "B", phases: ["cruise","recover","evade"] },
  { from: "TORPEDO", to: "CAPTAIN", what: "Solution ready · tubes loaded", tpl: "B", phases: ["attack"] },
  { from: "SONAR", to: "TORPEDO", what: "Bearing / AOB / classification", tpl: "B", phases: ["stalk","attack"] },
  { from: "SONAR", to: "NAVIGATOR", what: "Bearings for TMA plot", tpl: "A", phases: ["stalk","attack"] },
  { from: "SONAR", to: "ENGINEER", what: "Go silent · pump noise", tpl: "B", phases: ["stalk","evade"] },
  { from: "NAVIGATOR", to: "TORPEDO", what: "Own-ship course/speed", tpl: "A", phases: ["cruise","stalk","attack"] },
  { from: "NAVIGATOR", to: "ENGINEER", what: "Snorkel ETA · charge window", tpl: "B", phases: ["cruise"] },
  { from: "ENGINEER", to: "TORPEDO", what: "Tube serviceability · air", tpl: "A", phases: ["cruise","stalk","attack"] },
  { from: "CAPTAIN", to: "TORPEDO", what: "Fire & decoy orders", tpl: "B", phases: ["attack","evade"], urgent: true },
];

window.CREW_STATIONS_POOLS = [
  { station: "Sonar",     watch: 1, battle: 2 },
  { station: "Navigator", watch: 2, battle: 3 },
  { station: "Engineer",  watch: 3, battle: 5 },
  { station: "Torpedo",   watch: 4, battle: 7 },
  { station: "Captain (orderly)", watch: 1, battle: 2 },
];

/* Per-station per-phase actions — feeds the Stations-section heatmap.
   Intensity is an integer 1..7 echoing PHASES[i].loads. */
window.STATION_PHASE_ACTIONS = {
  CAPTAIN: {
    cruise:  ["Review patrol reports", "Set patrol grid", "Reassign idle crew to drills", "File BdU slips"],
    stalk:   ["Develop attack approach", "Authorise active ping", "Periscope sweeps (6–8 s)", "Target priority call"],
    attack:  ["Final scope observation", "Fire authorisation — 'Rohr X, Loss!'", "Bold order", "Immediate course change"],
    evade:   ["Evasion calls", "Decoy & Sieglinde orders", "Deep-dive authorisation", "Stufe 1 order"],
    recover: ["Receive damage report", "Casualty acknowledgement", "Set course (next grid or home)", "Log entry"],
  },
  SONAR: {
    cruise:  ["Sweep all bearings", "Log routine contacts", "FuMB-7 ESM scan", "Sonar maintenance"],
    stalk:   ["Lock target on KDB", "Classify via Geräuschbuch", "Bearing feed to Vorhaltrechner", "Track AOB shift"],
    attack:  ["Track torpedo run", "Confirm 'Aal läuft'", "Hit assessment", "Watch for counter-fire"],
    evade:   ["Track escort screws", "Decoy progress monitor", "Thermal layer cross", "Pump-noise warnings"],
    recover: ["Verify silence", "Log enemy retreat bearings", "Update Geräuschbuch entries"],
  },
  NAVIGATOR: {
    cruise:  ["Sun / Sonne fix", "Plot update", "Encode outbound HF burst", "Schlüsselgerät 51 decode"],
    stalk:   ["Build TMA plot from bearings", "ETA to attack position", "Doppler-shift watch", "Own-ship feed to TDC"],
    attack:  ["Own-ship course/speed feed", "Mark fire position on chart", "Log torpedo away"],
    evade:   ["Plot escape course", "Track decoy positions", "Note ASW response area"],
    recover: ["Set return course", "Log patrol summary entry"],
  },
  ENGINEER: {
    cruise:  ["Snorkel cycles", "Battery charge management", "Trim adjust", "Routine maintenance cards"],
    stalk:   ["Silent state Stufe 3", "Mode change electric → creep", "Pump cutoff prep"],
    attack:  ["Tube-fire trim compensation", "Compressed-air supply", "Speed-order response"],
    evade:   ["Emergency blow", "Stufe 1 silent discipline", "Deep-dive trim", "Damage suppression"],
    recover: ["Damage assessment", "Casualty triage", "Pump / cell / hatch repair", "Air-replenish cycle"],
  },
  TORPEDO: {
    cruise:  ["Tube inspections", "Wire-spool service", "Bold-VII reload check", "Inventory tally"],
    stalk:   ["Vorhaltrechner solution dev", "Type selection per target", "Salvo plan", "Wire-guide CRT prep"],
    attack:  ["Fire button on order", "Wire-guide manual fly (Lerche)", "Reload pressure", "Salvo timing"],
    evade:   ["Bold-VII launch on order", "Sieglinde stream / recover", "Quiet-tube discipline"],
    recover: ["Tube reload (slow)", "Bold-VII replenishment", "Inventory + damage tally"],
  },
};

window.OPEN_QUESTIONS = [
  { tag: "Q-new-H", state: "open", title: "Audio-tuning knob response curves",
    body: "EQ filter steepness, signal-band toggle interaction with sea state. Sonar tuning / playtest." },
  { tag: "Q-new-I", state: "open", title: "Thermal layer simulation depth",
    body: "Full physics (sound velocity gradient, refraction math) vs zone-based approximation? Engine-cost call." },
  { tag: "Q-new-J", state: "open", title: "Geräuschbuch live update during patrol",
    body: "Operator-amended margin notes, campaign-save persistence. Persistence story scope." },
  { tag: "Q-new-K", state: "open", title: "Easy-mode tooltip layer (cross-cutting)",
    body: "Pattern surfaced across periscope discipline, S-Gerät, sonar intercept, machinery bleed, Geräuschbuch. Needs top-level difficulty / accessibility decision." },
  { tag: "Q-new-B", state: "open", title: "Named-NCO cast list",
    body: "Personalities, regional German accents, backstories, voice profile training corpora. ~5–10 named men." },
  { tag: "Q-new-C", state: "open", title: "Sub-variant pool tables",
    body: "Per-variant crew pool sizes. Atlantik canonical; Küstenwolf, Silberfisch, Fernwolf, Walhall pending." },
  { tag: "Q-new-E", state: "open", title: "Camera-shake severity curve",
    body: "Calibration of 'subtle wobble' → 'real shake'; Das Boot hull-rattle bounds." },
  { tag: "Q-new-F", state: "open", title: "Meta-game command-engagement controls",
    body: "Time-compression toggle, engagement override, manual re-engage. Live as physical toggles on the plotting-table edge?" },
];

window.TONE_ANCHORS = [
  { head: "Quiet attrition", body: "Not action heroism. Long stretches of routine punctuated by brief terror." },
  { head: "Professional crew", body: "No martial bombast, no party iconography. The bridge crew is German aristocratic-military: disciplined, competent, fatigued." },
  { head: "Voice is the soul", body: "Every cross-station data exchange has a verbal component. Voice chat is the primary collaboration medium; buttons are formal backup." },
  { head: "Sound design carries fear", body: "No screen-shake. No bass-drop stinger. The depth-charge experience is what you hear — the propeller-wash above, the pressure-pop of distant detonations, the hull-creak." },
  { head: "The boat is the protagonist", body: "Crew comes and goes; key men matter; the Atlantik herself is the persistent character across a campaign." },
];

window.PREMISE_BLOCKS = [
  { head: "Setting", body: "1955–1958. A sixteen-year war that never ended after the Gersdorff bomb succeeded on 21 March 1943, killing Hitler and triggering the conservative-military coup that founded the Kaiserreich. The player faction is the Kriegsmarine U-boat arm." },
  { head: "The choice", body: "After the 1943 coup, the new German government made a fundamental strategic choice. With the Allies controlling the seas and the air, the only path to forcing a maritime decision was to commit to the submarine as the primary instrument of war at sea. Every naval Reichsmark not spent on coastal defence went into U-boats and U-boat technology — for twelve years, unbroken." },
  { head: "The result", body: "By 1955, a fleet of submarines vastly more capable than anything that existed in the wartime years. The Walter and closed-cycle diesel programs have pushed sustained submerged endurance to weeks rather than hours. Sensor systems have advanced to the point where a skilled crew can develop a complete tactical picture without ever raising a periscope. Weapons systems can engage targets the boat has never visually seen." },
  { head: "The threat", body: "The Allies have responded by pouring equivalent resources into surface warfare and ASW. A technological hothouse: every advance on one side produces an answer on the other. Allied ASW peak — escorts plus carriers plus helicopters plus sonobuoys plus dipping sonar plus the GIUK passive barrier." },
  { head: "What it isn't", body: "No swastikas. No party iconography. No atomic weapons operational on either side. The crew is professional military. The Kaiserreich's Imperial Eagle is the standard. The tone is Das Boot extended into a Cold War that stayed hot at sea." },
];
